project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: source.qmd
        text: Source
      - href: Dedication.qmd
        text: Dedication
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



